### ISSUE TITLE
Instalacja na serwerze

### ISSUE THREAD

**Issue by hagmen** [MK-PL/AllegroRSS#11]
Nie jest to problem z samym działaniem skryptu ale może ktoś powiedzieć czy da się to uruchomić na jakimś tanim, łatwo dostępnym serwerze np. VPS od nazwy? A jeśli tak to w jaki sposób. Może komuś się udało i podały instrukcje krok po kroku.

**Comment by MK-PL** [comment]
@hagmen Co prawda komentarz jest z maja, ale odpiszę, bo może komuś się to przyda - skrypt swego czasu testowałem na VPS nazwa.pl i ArubaCloud. Z tego, co patrzyłem, to można sobie wypróbować VPS na Aruba (https://www.arubacloud.pl/przetestuj-za-darmo.aspx). Tani VPS dalej jest też na nazwa.pl, płaci się 6,15zł za m-c. Oczywiście, nie są to jakieś wydajne maszyny, ale powinno wystarczyć na początek.
