### ISSUE TITLE
Zużycie zasobów

### ISSUE THREAD

**Issue by JuniorJPDJ** [MK-PL/AllegroRSS#15]
Posiadam uruchomiony od jakichś 35h generator RSSa odpytywany o kilka linków co minutę.
W tym czasie zaczał on już pożerać jakieś przeraźliwe ilości zasobów - spokojnie przekracza 5GB używanej pamięci ram, doi do 100% użycia 2-4 rdzeni procesora i ma aktualnie w swoim kontenerze uruchomione ponad 25 tysięcy procesów.

Jeżeli mógłbyś zdiagnozować i naprawić problem, to byłbym bardzo wdzięczny.

**Comment by JuniorJPDJ** [comment]
Po ograniczeniu ilości pamięci jaką ma do dyspozycji RSS postanowił się on kompletnie wysypać.
Ograniczyłem pamięć do 2GB, więc nie jest to jakoś mało.

**Comment by JuniorJPDJ** [comment]
Problemem są powstające w trakcie działania aplikacji procesy zombie (pytanie czemu taka sytuacja ma miejsce).
Rozwiązałem problem (a raczej obszedłem) stosując tini w kontenerze dockera.
Dobrze byłoby jednak, żebyś znalazł przyczynę powstawania procesów zombie i ją wyeliminował.

**Comment by MK-PL** [comment]
@JuniorJPDJ 
Dzięki za zgłoszenie, w wolnej chwili się tym zajmę. Ostatnio mam mało wolnego czasu, więc nie obiecuję, że to będzie załatwione szybko.
 
W skrypcie jest używany Electron jako przeglądarka działająca w ukryciu i gdy coś nawali w skrypcie lub na stronie, to teoretycznie funkcja odczytująca ([Nightmare](https://github.com/segmentio/nightmare)) w skrypcie powinna się przerwać i zamknąć proces Electron i wywołać kolejny (domyślnie są ustawione 3 próby). Prawdopodobnie skrypt AllegroRSS nie zamyka tych procesów Electron i potem wychodzi wysokie zużycie zasobów.
