### ISSUE TITLE
rss nie działa

### ISSUE THREAD

**Issue by karmon11** [MK-PL/AllegroRSS#16]
Jest chyba jakiś problem z generowaniem rss.

**Comment by sirozhkas** [comment]
Potwierdzam, cmd wywala po kilku/kilkunastu sekundach.

**Comment by kriseck** [comment]
Należałoby napisać - przestało działać po ostatnich aktualizacjach Windy.
Działają niektóre kanały, inne - nie. 

AllegroRSS-master\index.js:164
title: result[0].documentTitle

TypeError: Cannot read property 'documentTitle' of undefined
    at C:\Program Files\nodejs\node_modules\AllegroRSS-master\index.js:164:50
    at C:\Program Files\nodejs\node_modules\AllegroRSS-master\node_modules\vo\index.js:46:19
    at next (C:\Program Files\nodejs\node_modules\AllegroRSS-master\node_modules\vo\lib\pipeline.js:33:38)
    at Immediate.<anonymous> (C:\Program Files\nodejs\node_modules\AllegroRSS-master\node_modules\co\index.js:52:14)
    at runCallback (timers.js:705:18)
    at tryOnImmediate (timers.js:676:5)
    at processImmediate (timers.js:658:5)

**Comment by MK-PL** [comment]
Dziękuję za zgłoszenia, wrzuciłem poprawkę 0f38e9e. Proszę sprawdzić, czy teraz działa. Ostatnio mam bardzo mało czasu do rozdysponowywania z wielu powodów, więc uprzedzam, że jakiekolwiek przyszłe poprawki mogą się opóźnić.

**Comment by kriseck** [comment]
Dziękuję(my) za szybką reakcję - działa! Wszystkie kanały, które miałem (około 20tu) działają.
