### ISSUE TITLE
Błąd w generowaniu kanału RSS

### ISSUE THREAD

**Issue by derby7** [MK-PL/AllegroRSS#2]
Przy generowaniu kanału RSS Allegro dla braku jakichkolwiek przedmiotów wyskakuje informacja zwrotna "Nie można odczytać podanej strony!" i nie da się skorzystać z kanału. Taka opcja przydałaby się przy wyszukiwaniu rzeczy, których aktualnie nie ma.
Tak w ogóle to dziękuję za super generator :-)

**Comment by MK-PL** [comment]
Dziękuje za komentarz :-)

Dorobię odpowiedni warunek w kodzie.

**Comment by derby7** [comment]
Bardzo proszę o dołączenie brakujących plików.

**Comment by MK-PL** [comment]
Poprawkę wrzuciłem w zeszły wtorek, proszę sprawdzić.

**Comment by derby7** [comment]
Dotarło do mnie, że po podmianie plików na nowe powinienem ponownie użyć polecenia npm install.

A czy mógłby Pan tak zmodyfikować generator, żeby mimo braku wyników wyszukiwania w Allegro generator wygenerował kanał RSS z zerowymi wynikami? W tej chwili co prawda pojawia się informacja "W podanym adresie URL nie ma obecnie aktywnych aukcji.", ale kanał RSS nie jest generowany, przez co nie można użyć go w czytniku kanałów RSS.

**Comment by MK-PL** [comment]
Mogę zmodyfikować :-)
Wrzuciłem poprawkę przed chwilą.

**Comment by derby7** [comment]
Przetestowałem przed chwilą ostatnią modyfikację i muszę stwierdzić... 
Właśnie produkowałem się, że modyfikacja nie chce działać, a tu po 10 minutach od pojawienia się mojej fikcyjnej aukcji, którą założyłem dla celów przetestowania generatora, jednak zadziałało.
Bardzo serdecznie dziękuję za dobrą robotę.
Życzę dużo szczęścia i radości :-)
Dobrych życzeń nigdy za wiele :-)

**Comment by MK-PL** [comment]
Dziękuję i cieszę się, że działa, pozdrawiam :-)
