### ISSUE TITLE
Cannot find module...

### ISSUE THREAD

**Issue by cropp1** [MK-PL/AllegroRSS#20]
Po instalacji, czyli komendzie "npm install", nie mogę przejść dalej. Dostaję komunikat "cannot find module C:\Program Files\nodejs\node_modules\npm\index.js" 
![node](https://user-images.githubusercontent.com/57813787/68973845-92d17480-07ef-11ea-804b-56abe3acc3f9.png)

**Comment by MK-PL** [comment]
@cropp1 Jeśli dobrze zrozumiałem komunikaty, to próbujesz uruchomić skrypt z domyślnego katalogu npm `C:\Program Files\nodejs\node_modules\npm\`, w którym nie ma pliku `index.js` i stąd jest ten błąd.
Musisz wejść w konsoli w katalog z skryptem i w nim spróbować uruchomić skrypt. Najłatwiej będzie wpisać w konsoli `cd <ścieżka do katalogu>` np. `cd C:\skrypt` i potem `node index.js`.
