### ISSUE TITLE
Samodzielne zatrzymanie skryptu

### ISSUE THREAD

**Issue by swietliczek** [MK-PL/AllegroRSS#21]
Witam.
Dziękuję za kawał dobrej roboty!

Mam problem z poprawnym działaniem skryptu.
Zainstalowałem(folder: C:\alle, tak jak w instrukcji, pobrało się co miało się pobrać,) i uruchomiłem na komputerze(I7-4770R/16GB ram/Win 7). Kanały Rss aktualizują się.
Problem w tym, że po pewnym czasie(w nieregularnych odstępach) skrypt się zatrzymuje i wyświetla:
C:\alle\index.js:165
                                title: result[0].documentTitle,
                                                 ^

TypeError: Cannot read property 'documentTitle' of undefined
    at C:\alle\index.js:165:50
    at C:\alle\node_modules\←[4mvo←[24m\index.js:46:19
    at next (C:\alle\node_modules\←[4mvo←[24m\lib\pipeline.js:33:38)
    at Immediate.<anonymous> (C:\alle\node_modules\←[4mco←[24m\index.js:52:14)
←[90m    at processImmediate (internal/timers.js:439:21)←[39m

C:\alle>node index.js
Uruchomiono serwer na porcie 4000

Po wpisaniu "node index.js" skrypt dalej działa do kolejnego zatrzymania.
Zainstalowałem testowo na J5005/16GB/Win10 i sytuacja jest podobna, średnio po kilkudziesięciu minutach skrypt zatrzymuje się.
Co może być tego przyczyną? Zasoby sprzętowe i wydajność chyba nie stwarzają tu problemu.
Darek

**Comment by swietliczek** [comment]
Wiem w czym problem.
Powodem zatrzymania skryptu(skrypt zatrzymuje się na pierwszej próbie) jest próba pobrania oferty która jest już niedostępna jak na obrazku:

![Nowy obraz mapy bitowej (4)](https://user-images.githubusercontent.com/61112191/74639182-b64ce800-516d-11ea-8a53-6e062bedbcce.png)

Teoretycznie Allegro informuje(po wejściu na stronę sprzedającego), że sprzedający ma jeszcze wystawioną jedną ofertę, a praktycznie oferta nie jest już dostępna.

W moim przypadku jeden kanał(sprzedający) generował takie zatrzymanie, po jego usunięciu wszystko kanały są odświeżane poprawnie.
Można by sobie z tym poradzić ustawiając odświeżanie ofert danego sprzedającego raz na tydzień(mam nadzieję, że przez ten czas Allegro zaktualizuje stan ofert danego sprzedającego) i czekać aż na kolejnym sprzedającym skrypt się nie zatrzyma.

Możliwa jest zmiana skryptu tak by po trzeciej nieudanej próbie przechodził do pobierania kolejnego kanału?

**Comment by MK-PL** [comment]
Witaj @swietliczek. Dziękuję za zgłoszenie. Wrzuciłem poprawkę, która powinna naprawić błąd w przypadku, gdy nie ma żadnej aktywnej aukcji. Sprawdź proszę, pozdrawiam.

**Comment by swietliczek** [comment]
Witam.
Dziękuję za dodanie poprawki.
Pojawił się inny problem, prawdopodobnie generator nie widzi i nie wyświetla nowych ofert.
Ostatnio aktualizowałem kanały RSS Allegro(mam ich kilkadziesiąt) z miesiąc temu - mniej więcej w tym czasie przestał działać generator.
Od nowa zainstalowałem wczorajszy poprawiony generator.
Skrypt we wszystkich obserwowanych kanałach znalazł tylko po jednej nowe ofercie, ale nie potrafił jej opisać i wyświetlić:
![Nowy obraz mapy bitowej](https://user-images.githubusercontent.com/61112191/77250161-3cb18980-6c46-11ea-9658-e2cd9930b474.jpg)
Tak jest we wszystkich kanałach.

Po kliknięciu na "Pokaż wszystkie elementy" wyświetlane są tylko oferty z aktualizacji miesiąc temu(około 22-02-2020).

**Comment by MK-PL** [comment]
@swietliczek - wrzuciłem kolejną poprawkę. Sprawdź proszę. Jeżeli nie zadziała, podeślij adresy, pod którymi sprawdzasz skrypt.

**Comment by swietliczek** [comment]
Teraz jest OK.
Jeszcze raz dziękuję za kawał dobrej pracy pro bono!
