### ISSUE TITLE
Skrypt przestał działać

### ISSUE THREAD

**Issue by kriseck** [MK-PL/AllegroRSS#22]
Zamyka się przy próbie połączenia. Wczoraj wieczorem wszystko było jeszcze ok. W nocy Allegro dodało opcję wyszukiwania kilku przedmiotów u jednego użytkownika. Stąd problem.

(trzeba wyłączyć automatyczne tłumaczenie na stronie, bo głupoty wychodzą...)

**Comment by kl0007** [comment]
@MK-PL - czy jest szansa na poprawkę? :)

**Comment by MK-PL** [comment]
@kriseck @kl0007 - wrzuciłem dzisiaj poprawkę. Sprawdźcie proszę, czy działa dobrze.

**Comment by kriseck** [comment]
U mnie wygenerowało same puste wiadomości... Używam QuiteRSS

**Comment by kl0007** [comment]
@MK-PL - skrypt generuje puste RSSy :(

**Comment by MK-PL** [comment]
@kriseck @kl0007 - wrzuciłem kolejną poprawkę. Sprawdźcie proszę. Jeżeli nie zadziała, podeślijcie adresy, pod którymi sprawdzacie skrypt.

**Comment by kl0007** [comment]
@MK-PL - śliczne dzięki - wygląda na to, że działa! :)
