### ISSUE TITLE
TypeError: Cannot read property 'documentTitle' of undefined

### ISSUE THREAD

**Issue by xylorin** [MK-PL/AllegroRSS#24]
Od kilku dni (prawdopodobnie bo któreś z aktualizacji Windowsa) skrypt wywala błąd jak niżej:

**TypeError: Cannot read property 'documentTitle' of undefined**

**Comment by MK-PL** [comment]
Dzięki za zgłoszenie @xylorin. Wrzuciłem dzisiaj poprawkę d540dcc. Sprawdź proszę, czy działa ok.

**Comment by xylorin** [comment]
> Dzięki za zgłoszenie @xylorin. Wrzuciłem dzisiaj poprawkę [d540dcc](https://github.com/MK-PL/AllegroRSS/commit/d540dcce7b5ba58353729e7c17c5f91624259f25). Sprawdź proszę, czy działa ok.

Działa! Dzięki
