### ISSUE TITLE
Skrypt przestał działać

### ISSUE THREAD

**Issue by ddand** [MK-PL/AllegroRSS#3]
Dzień dobry, wygląda na to, że po ostatnich zmianach w API skrypt przestał działać - otrzymuję komunikat o braku połączenia przy próbie pobrania nowych aukcji.

**Comment by MK-PL** [comment]
Dziękuję za zgłoszenie, poprawiłem skrypt. Proszę sprawdzić, czy teraz działa.

**Comment by ddand** [comment]
Bardzo dziękuję, wszystko działa!
