### ISSUE TITLE
Problem ze sponsorowanymi aukcjami

### ISSUE THREAD

**Issue by mmdl** [MK-PL/AllegroRSS#4]
Przy adresie `https://allegro.pl/kategoria/mikrokomputery-254498?startingTime=1&order=m` pobierane są tylko sponsorowane aukcje i za każdym razem mają chyba inny identyfikator, więc traktowane są jako nowe przez czytnik RSS.

**Comment by MK-PL** [comment]
Dziękuję za zgłoszenie.
Adresy URL sponsorowanych aukcji mają inny identyfikator przy każdym odczycie, jednakże zawierają stały adres URL do aukcji. W skrypcie dopisałem odpowiedni warunek, który wyłuskuje ten stały adres do kanału RSS. Proszę sprawdzić, czy działa teraz dobrze.

Pozdrawiam
