### ISSUE TITLE
problem z generowaniem

### ISSUE THREAD

**Issue by karmon11** [MK-PL/AllegroRSS#5]
Korzystałem z tego rss przez dłuższy czas bez problemu aż nagle z dnia na dzień przestał działać. Po wygeneruj w localhoscie dane są raz pobierane i koniec.

**Comment by MK-PL** [comment]
@karmon11 Wprowadziłem poprawkę, proszę sprawdzić czy teraz działa.

**Comment by karmon11** [comment]
Działa :) Dzięki!
