### ISSUE TITLE
Type Error: cannort read property 'documentTitle' or undefined

### ISSUE THREAD

**Issue by xylorin** [MK-PL/AllegroRSS#7]
Skrypt działał jak złoto przez pare miesięcy, kilka dni temu (być może po aktualizacji windowsa) wywala błąd jak w tytule. Jakieś pomysły?

**Comment by darektci** [comment]
Podłączam się, mam ten sam problem 
Błąd wygląda tak:

`Uzyskano połączenie z podaną stroną i pobrano z niej dane
GENEROWANIE RSS - koniec dla adresu URL: https://allegro.pl/kategoria/sprzet-audio-dla-domu-uszkodzone-14328?strategy=NO_FALLBACK&order=n
/usr/local/lib/node_modules/AllegroRSS/index.js:151
                                title: result[0].documentTitle,
                                                 ^

TypeError: Cannot read property 'documentTitle' of undefined
    at /usr/local/lib/node_modules/AllegroRSS/index.js:151:50
    at /usr/local/lib/node_modules/AllegroRSS/node_modules/vo/index.js:46:19
    at next (/usr/local/lib/node_modules/AllegroRSS/node_modules/vo/lib/pipeline.js:33:38)
    at Immediate.<anonymous> (/usr/local/lib/node_modules/AllegroRSS/node_modules/co/index.js:52:14)
    at runCallback (timers.js:705:18)
    at tryOnImmediate (timers.js:676:5)
    at processImmediate (timers.js:658:5)`

**Comment by MK-PL** [comment]
Dziękuję za zgłoszenie, wprowadziłem poprawki w skrypcie, powinien teraz znów działać.

**Comment by xylorin** [comment]
Rzeczywiście, znów działa wyśmienicie. Dziękuję!

**Comment by darektci** [comment]
Potwierdzam działa . Dziękuję
