### ISSUE TITLE
Nieskończona próba połączenia.

### ISSUE THREAD

**Issue by Ultimaa** [MK-PL/AllegroRSS#8]
Nie wiem czy problem występuje tylko u mnie, lecz za każdym razem kiedy próbuje wygenerować kanał RSS dostaje komunikat:
"GENEROWANIE RSS - start dla adresu URL:  ADRES-WWW
1. Próba połączenia"
Po chwili komunikat się powtarza i tak w nieskończoność.  System to UBUNTU 18.04.

**Comment by MK-PL** [comment]
Dziękuję za zgłoszenie. Sprawdzałem u siebie na Ubuntu i skrypt działał. Potrzebowałbym więcej szczegółów (np. jaki URL), żeby ustalić co nie gra.

**Comment by Ultimaa** [comment]
![screenshot at 2019-01-24 14-03-43](https://user-images.githubusercontent.com/29726818/51680031-ecf31600-1fe0-11e9-9b30-7493279b7b4c.png)

Wklejany link to [https://allegro.pl/kategoria/sony-psp-konsole-122302?order=n&bmatch=baseline-n-ele-1-0-1130&offerTypeBuyNow=1](url)

**Comment by MK-PL** [comment]
@Ultimaa Czy ten problem w dalszym ciągu występuje? Wyglądało na to, że mógł to być chwilowy brak połączenia z serwisem Allegro.
