### ISSUE TITLE
Brak cen w wynikach

### ISSUE THREAD

**Issue by fakk3** [MK-PL/AllegroRSS#9]
Po wygenerowaniu kanału rss większość pozycji w wynikach nie posiada ceny, tylko stan i np. wersję językową. W zasadzie cena jest najważniejsza w tym wypadku. Da się to jakoś naprawić? W załączniku screen.

**Comment by MK-PL** [comment]
Dziękuję za zgłoszenie, wrzuciłem poprawkę, proszę sprawdzić: e507416733268f5311cec60e96a65053dee75bc1

**Comment by fakk3** [comment]
Ceny już się pojawiają. Dziękuję. Jeszcze jedna sugestia. Czy dało by się dodać do wyniku wyszukiwania nazwę sprzedającego? Wbrew pozorom dużo to daje, ponieważ obserwując często powtarzające się aukcje zwyczajnie można je sobie omijać wiedząc co to za sprzedawca i że nie ma sensu na nie wchodzić.

**Comment by MK-PL** [comment]
@fakk3 ~~W ostatnim commicie 50d35c99e31eb5f0d01a863cb2774c8468c620f3 dodałem nazwę sprzedającego. Sprawdź proszę, czy wszystko działa ok, pozdrawiam!~~
EDIT: Musiałem nazwę sprzedającego na razie wycofać, ponieważ wywalała skrypt.
